sudo: required

services: [docker]

cache:
  directories: [$HOME/.cache/snapcraft/]

script:
  - ./scripts/snap-in-docker.sh
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install *amd64*.snap --dangerous
