dist: xenial

language: rust

addons:
  apt:
    packages:
    - cmake
  snaps:
  - name: snapcraft
    classic: true

jobs:
  include:
    - stage: "build snaps"
      name: amd64
      script:
        - /snap/bin/snapcraft clean
        - /snap/bin/snapcraft --target-arch amd64 && sudo snap install *.snap --dangerous
    - name: i386
      script:
        - /snap/bin/snapcraft clean
        - /snap/bin/snapcraft --target-arch i386
    - name: armhf
      script:
        - /snap/bin/snapcraft clean
        - /snap/bin/snapcraft --target-arch armhf
    - name: arm64
      script:
        - /snap/bin/snapcraft clean
        - /snap/bin/snapcraft --target-arch arm64
