dist: xenial

language: rust

addons:
  apt:
    packages:
    - cmake
  snaps:
  - name: snapcraft
    classic: true

env:
  - ARCHITECTURE=amd64
  - ARCHITECTURE=i386
  - ARCHITECTURE=armhf
  - ARCHITECTURE=arm64

script:
  - /snap/bin/snapcraft clean
  - travis_wait 50 /snap/bin/snapcraft --target-arch $ARCHITECTURE
  # Test the installation. The host is amd64 so that's the only one
  # installable.
  - |
    if [ "$ARCHITECTURE" = "amd64" ]; then
      sudo snap install *.snap --dangerous
    fi
  # Publish to the edge channel.
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
      # Decrypt the login credentials.
      openssl aes-256-cbc -K $encrypted_6f2c54a3a0c1_key -iv $encrypted_6f2c54a3a0c1_iv -in snapcraft-login.enc -out snapcraft-login -d
      snapcraft login --with snapcraft-login
      snapcraft push *.snap --release edge
    fi
