name: parity
# Get the version from the parity part.
adopt-info: parity
summary: The fast, light, and robust EVM and WASM client.
description: |
  Built for mission-critical use: Miners, service providers, and exchanges
  need fast synchronisation and maximum uptime. Parity Ethereum provides the
  core infrastructure essential for speedy and reliable services.

confinement: strict

apps:
  parity:
    command: parity
    plugs:
      - network
      - network-bind
      - removable-media

parts:
  parity:
    source: https://github.com/paritytech/parity-ethereum.git
    source-tag: master
    plugin: nil
    build-packages:
      - curl
      - g++
      - libudev-dev
      - libudev1
      - cmake
      - libc6
      - libstdc++6
    override-pull: |
       snapcraftctl pull
       version="$(git describe --dirty --always)"
       snapcraftctl set-version $version
    override-build: |
       curl https://sh.rustup.rs -sSf | sh -s -- -y
       $HOME/.cargo/bin/cargo build --release --features final
       mkdir $SNAPCRAFT_PART_INSTALL/bin
       mv target/release/parity $SNAPCRAFT_PART_INSTALL/bin/
